### ISSUE TITLE
Plugins get not persisted

### ISSUE THREAD

**Issue by nefarius** [rez0n/docker-nodebb#49]
Good day!

I'm facing the issue, that plugins I install after the initial setup vanish after container restart.

The settings are kept (apparently persisted in the Redis DB) but the actual plugins themselves (thos who are not shipped in the default installation) are gone.

Do you have the same experience? Am I doing something wrong? Here's the compose file I'm experimenting with:

```yaml
version: "3"

services:
  forums-test:
    image: nibrev/nodebb:stable
    container_name: forums-test.example.org-app
    restart: always
    networks:
      - web
      - redis-net
    depends_on:
      - redis
    volumes:
      - ./data:/data
    environment:
      - URL="https://forums-test.example.org"
      - DATABASE="redis"
      - DB_HOST="redis"
      - DB_NAME="0"
      - DB_PORT="6379"
    labels:
      - traefik.enable=true
      - traefik.http.routers.forums-test.rule=Host(`forums-test.example.org`)
      - traefik.http.routers.forums-test.entrypoints=web-secure
      - traefik.http.routers.forums-test.tls=true
      - traefik.http.routers.forums-test.tls.certresolver=le
      - traefik.http.services.forums-test.loadbalancer.server.port=4567

  redis:
    image: redis:alpine
    container_name: forums-test.example.org-db
    hostname: redis
    restart: always
    networks:
      - redis-net
    volumes:
      - ./redis/data:/data
    labels:
      - traefik.enable=false

networks:
  redis-net:
  web:
    external: true

```

I experimented with mounting the `node_modules` as volume but I get all sorts of weird errors with that.

Any help is highly appreciated.

Cheers!
